

name: Main workflow for Food Orderring System

on:
  push:
    branches:
      - 'ft/*'
      - 'Comflict/Check'
      - 'development'
      - 'update/*'
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    uses: ./.github/workflows/build.yaml

  terraform:
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/change_mangment.yaml